version: '3'
services:
  mysql-1:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=orders
    ports:
      - 3306:3306  
  mysql-2:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=shippings
    ports:
      - 3307:3306        
  mykafka:
    image: apache/kafka:3.7.0
    ports:
      - 9092:9092    

# docker compose up -d 
# docker compose down
